apiVersion: apps/v1
kind: Deployment
metadata:
  name: woof-woof-app-deployment
  labels:
    app: woofwoof
spec:
  replicas: 2
  selector:
    matchLabels:
      app: woofwoof
  template:
    metadata:
      labels:
        app: woofwoof
    spec:
      containers:
      - name: backendapi
        image: 783966730108.dkr.ecr.us-east-1.amazonaws.com/computefest2021:woofwoof-backend-api
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
      - name: embeddingsearch
        image: 783966730108.dkr.ecr.us-east-1.amazonaws.com/computefest2021:woofwoof-embedding-search
        imagePullPolicy: Always
        ports:
        - containerPort: 9010
      - name: modelserver
        image: 783966730108.dkr.ecr.us-east-1.amazonaws.com/computefest2021:woofwoof-model-server
        imagePullPolicy: Always
        ports:
        - containerPort: 9020
      - name: frontend
        image: 783966730108.dkr.ecr.us-east-1.amazonaws.com/computefest2021:woofwoof-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: woof-woof-app-service
spec:
  type: LoadBalancer
  selector:
    app: woofwoof
  ports:
    - name: backendapi
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: embeddingsearch
      protocol: TCP
      port: 9010
      targetPort: 9010
    - name: modelserver
      protocol: TCP
      port: 9020
      targetPort: 9020
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80